version: "3.8"

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-backend:task4
    ports:
      - "5252:5252"

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-frontend:task4
    ports:
      - "9000:9000"
    depends_on:
      - backend
